post/urls.py
from django.urls import path
from .views import create_event, create_project,create_thesis, view_event, view_thesis, view_project, delete_event, delete_project, delete_thesis, edit_project, edit_event, edit_thesis

app_name = 'post'

urlpatterns = [
    path("create_event/", create_event, name="create_event"),
    path("create_project/", create_project, name="create_project"),
    path("create_thesis/", create_thesis, name="create_thesis"),
    path("view_event/<str:pk>", view_event, name="view_event"),
    path("view_project/<str:pk>", view_project, name="view_project"),
    path("view_thesis/<str:pk>", view_thesis, name="view_thesis"),
    path("delete_event/<str:pk>", delete_event, name="delete_event"),
    path("delete_project/<str:pk>", delete_project, name="delete_project"),
    path("delete_thesis/<str:pk>", delete_thesis, name="delete_thesis"),
    path("edit_event/<str:pk>", edit_event, name="edit_event"),
    path("edit_project/<str:pk>", edit_project, name="edit_project"),
    path("edit_thesis/<str:pk>", edit_thesis, name="edit_thesis"),
]

unicolabhub/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("home/", lambda request: redirect("home")),
    path('user/', include('user.urls')),
    path('post/', include('post.urls')),
    path('collaboration/', include('collaboration.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register_user, name='register_user'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('update_profile/', views.update_user, name='update_profile'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('update_profile_pic/', views.update_profile_pic, name='update_profile_pic'),
    path('delete_profile_pic/', views.delete_profile_pic, name='delete_profile_pic'),
]

user/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class CollabUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    collaborator_phone = models.CharField(max_length=20, default='', blank=True)
    collaborator_department = models.CharField(max_length=20, default='', blank=True)
    collaborator_university = models.CharField(max_length=20, default='', blank=True)
    collaborator_date_of_birth = models.DateField(blank=True, null=True)
    collaborator_university_id = models.CharField(max_length=20, default='', blank=True)
    collaborator_type = models.CharField(max_length=20, default='', blank=True)
    collaborator_about = models.TextField(default='', blank=True)

    collaborator_joined_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return (self.user.username+" "+self.collaborator_university+" "+self.collaborator_university_id)


class Opinion(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    opinion = models.TextField(default='')
    timestamp = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    post = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.opinion[0:20]

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import CollabUser

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']

class CollabUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CollabUser
        fields = '__all__'
        exclude = ('user',)
        widgets = {
            'collaborator_date_of_birth': forms.DateInput(
                attrs={'placeholder': 'YYYY-MM-DD'} # Visible hint
            )

        }

user/views.py
import os
from itertools import chain
import random

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import CollabUser
from post.models import Event, Project, Thesis
from collaboration.models import Collaborator


# user registration view
def register_user(request):
    if request.method == 'POST':
        # Get data from the form
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        # check pass & confirm pass
        if password != confirm_password:
            messages.error(request, "Passwords do not match.")
            return redirect('user:register_user')

        # check if username exists
        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already taken.")
            return redirect('user:register_user')

        # create user
        user = User.objects.create_user(username=username, password=password)
        user.is_staff = False  # Cannot access admin
        user.is_superuser = False  # Definitely not admin
        user.save()

        # register done msg
        messages.success(request, "Registration successful! You can now log in.")
        return redirect('user:login_user')

        # render reg form for GET method
    return render(request, 'user/register_form.html')


# login view
def login_user(request):
    if request.method == "POST":
        # get data from form
        username = request.POST.get("username")
        password = request.POST.get("password")
        # if no user, return none
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            # no login msg
            messages.error(request, "Invalid credentials")
            return render(request, "user/login_form.html")
    else:
        return render(request, "user/login_form.html")


# logout view
def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out.")
    return redirect('home')


# profile view
@login_required
def user_profile(request):
    user = request.user
    profile = CollabUser.objects.get(user=user)
    if request.user.is_authenticated:
        events = Event.objects.all()
        projects = Project.objects.all()
        theses = Thesis.objects.all()

        for e in events:
            e.content_type = "Event"
            e.date_field = e.created_at
        for p in projects:
            p.content_type = "Project"
            p.date_field = p.created_at
        for t in theses:
            t.content_type = "Thesis"
            t.date_field = t.created_at

        feed_items = list(chain(events, projects, theses))

        feed_items = list([fi for fi in feed_items if fi.organizer.user == user])

        # 🎲 Add slight random variation to sort key
        def sort_key(item):
            # Random factor between -300 and +300 seconds (±5 minutes)
            random_offset = random.uniform(-300, 300)
            # Apply offset to timestamp
            return item.date_field.timestamp() + random_offset

        # Sort by adjusted key descending (newer + randomness)
        feed_items.sort(key=sort_key, reverse=True)
    return render(request, 'user/user_profile.html', {'profile': profile, 'feed_items': feed_items})


# update profile
@login_required
def update_user(request):
    user = request.user
    profile = CollabUser.objects.get(user=user)

    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone_number = request.POST.get('collaborator_phone')
        department = request.POST.get('collaborator_department')
        university = request.POST.get('collaborator_university')
        university_id = request.POST.get('collaborator_university_id')
        date_of_birth = request.POST.get('collaborator_dob')
        type = request.POST.get('collaborator_type')
        about = request.POST.get('collaborator_about')
        user.username = username
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        profile.collaborator_phone = phone_number
        profile.collaborator_department = department
        profile.collaborator_university = university
        profile.collaborator_university_id = university_id
        profile.collaborator_date_of_birth = date_of_birth
        profile.collaborator_type = type
        profile.collaborator_about = about
        user.save()
        profile.save()
        return redirect('user:user_profile')


    return render(request, 'user/update_profile.html', {
        'user': user,
        'profile': profile
    })

# delete user
@login_required
def delete_user(request):
    if request.method == "POST":
        password = request.POST.get("password")
        user = request.user

        if user.check_password(password):
            username = user.username

            logout(request)
            user.delete()

            messages.success(request, f"User '{username}' account deleted successfully.")
            return redirect('home')
        else:
            messages.error(request, "Incorrect password. Please try again.")

    return render(request, "user/delete_confirmation.html")

def update_profile_pic(request):
    profile = CollabUser.objects.get(user=request.user)
    if request.method == "POST":
        picture = request.FILES.get("profile_picture")
        path = None
        if profile.profile_pic:
            path = profile.profile_pic.path
        profile.profile_pic = picture
        profile.save()
        if path != None:
            os.remove(path)
        return redirect('user:user_profile')
    return render(request, 'user/change_profile_pic.html', {
        'profile': profile
    })

def delete_profile_pic(request):
    profile = CollabUser.objects.get(user=request.user)
    if request.method == "POST":
        path = None
        if profile.profile_pic:
            path = profile.profile_pic.path
        profile.profile_pic = None
        if path != None:
            os.remove(path)
            return redirect('user:user_profile')
    return render(request, 'user/delete_profile_pic.html', {'profile': profile})

user/templates/user/change_profile_pic.html
{% extends 'base.html' %}

{% block title %}
Profile Picture Update
{% endblock %}

{% block content %}
<div class="container"
     style="margin-top: 60px; max-width: 60em; box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px; padding: 30px; border-radius: 15px;">

    <h1 style="text-align:center;">Update Profile Picture</h1>

    <div class="row vh-80 align-items-center justify-content-center">
        {% if profile.profile_pic %}
            <img src="{{ profile.profile_pic.url }}" alt="Profile Picture" width="400" class="rounded mb-2 img-thumbnail">
        {% else %}
            <img src="https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=Oliver" alt="No Profile Picture" width="400" class="rounded mb-2 img-thumbnail">
        {% endif %}
    </div>


    <form method="POST" enctype="multipart/form-data" action="{% url 'user:update_profile_pic' %}" style="margin-top: 20px;">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label" for="profile_picture">Profile Picture: </label>
            <input type="file" class="form-control" name="profile_picture" id="profile_picture" accept="image/*" required>
        </div>
        <button type="submit">Save Changes</button>
        <!--    login error message-->
        {% if messages %}

        {% for message in messages %}
        <br>
        <br>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}

        {% endif %}

    </form>

</div>

{% endblock %}

user/templates/user/delete_confirmation.html
{% extends 'base.html' %}

{% block title %}
{% if user.is_authenticated %}
UniColabHub - Delete Account : {{user.username}}
{% else %}
Delete Account
{% endif %}
{% endblock %}

{% block content %}
<form method="POST" style="max-width: 400px; margin: auto; margin-top: 40px;">
    {% csrf_token %}
    <h3>Confirm Account Deletion</h3>
    <p>Please enter your password to confirm deleting your account.</p>

    <div class="mb-3">
        <input
                type="password"
                name="password"
                class="form-control"
                placeholder="Password"
                required
                autofocus
        >
    </div>

    <button type="submit" class="btn btn-danger w-100">Delete My Account</button>

    {% if messages %}
    <br>
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
</form>

{% endblock %}

user/templates/user/delete_profile_pic.html
{% extends 'base.html' %}

{% block title %}
Profile Picture Delete
{% endblock %}

{% block content %}
<div class="container"
     style="margin-top: 60px; max-width: 60em; box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px; padding: 30px; border-radius: 15px;">

    <h1 style="text-align:center;">Delete Profile Picture</h1>

    <div class="row vh-80 align-items-center justify-content-center">
        {% if profile.profile_pic %}
            <img src="{{ profile.profile_pic.url }}" alt="Profile Picture" width="400" class="rounded mb-2 img-thumbnail">
        {% else %}
            <img src="https://via.placeholder.com/130?text=No+Image" alt="No Profile Picture" width="400" class="rounded mb-2 img-thumbnail">
        {% endif %}
    </div>


    <form method="POST" enctype="multipart/form-data" action="{% url 'user:update_profile_pic' %}" style="margin-top: 20px;">
        {% csrf_token %}
        <div class="mb-3">
            Do you want to delete your profile picture?
        </div>
        <button type="submit">Save Changes</button>
        <!--    login error message-->
        {% if messages %}

        {% for message in messages %}
        <br>
        <br>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}

        {% endif %}

    </form>

</div>

{% endblock %}

user/templates/user/login_form.html
{% extends 'base.html' %}

{% block title %}
Login Form
{% endblock %}

{% block content %}
<div class="container"
     style="margin-top: 60px; max-width: 500px; box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px; padding: 30px; border-radius: 15px;">

    <h1 style="text-align:center;">Login</h1>

    <form method="POST" action="{% url 'user:login_user' %}" style="margin-top: 20px;">
        {% csrf_token %}
        <div class="mb-3">
            <input type="text" class="form-control" name="username" placeholder="Username" required>
        </div>
        <div class="mb-3">
            <input type="password" class="form-control" name="password" placeholder="Password" required>
        </div>
        <div style="text-align: center;">
            <button type="submit" class="btn btn-primary">Submit</button>
            <p style="margin-top: 20px;">Or</p>
            <h6>Don't have an account?</h6>
            <a href="{% url 'user:register_user' %}" class="btn btn-primary">Register Now</a>
        </div>

        <!--    login error message-->
        {% if messages %}

        {% for message in messages %}
        <br>
        <br>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}

        {% endif %}

    </form>

</div>

{% endblock %}

user/templates/user/update_profile.html
{% extends 'base.html' %}

{% block title %}
Profile Update
{% endblock %}

{% block content %}
<div class="container"
     style="margin-top: 60px; max-width: 60em; box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px; padding: 30px; border-radius: 15px;">

    <h1 style="text-align:center;">Update Profile</h1>

    <form method="POST" action="{% url 'user:update_profile' %}" style="margin-top: 20px;">
        {% csrf_token %}

        <h3>Account Info</h3>
        <div class="mb-3">
            <label class="form-label" for="username">Username: </label>
            <input type="text" value="{{ user.username }}" class="form-control" name="username" id="username" placeholder="Username" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="email">Email address:</label>
            <input type="email" value="{{ user.email }}" class="form-control" name="email" id="email" placeholder="Email address" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="first_name">First name:</label>
            <input type="text" value="{{ user.first_name }}" class="form-control" name="first_name" id="first_name" placeholder="First name" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="last_name">Last name:</label>
            <input type="text" value="{{ user.last_name }}" class="form-control" name="last_name" id="last_name" placeholder="Last name" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="collaborator_phone">Phone:</label>
            <input type="tel" value="{{ profile.collaborator_phone }}" class="form-control" name="collaborator_phone" id="collaborator_phone" placeholder="Phone" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="collaborator_department">Department:</label>
            <input type="text" value="{{ profile.collaborator_department }}" class="form-control" name="collaborator_department" id="collaborator_department" placeholder="Department" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="collaborator_university">University:</label>
            <input type="text" value="{{ profile.collaborator_university }}" class="form-control" name="collaborator_university" id="collaborator_university" placeholder="University" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="collaborator_dob">Date of birth:</label>
            <input type="date" value="{{ profile.collaborator_date_of_birth|date:'Y-m-d' }}" class="form-control" name="collaborator_dob" id="collaborator_dob" required>
        </div>
        <div class="mb-3">
            <label class="form-label" for="collaborator_university_id">University id: </label>
            <input type="text" value="{{ profile.collaborator_university_id }}" class="form-control" name="collaborator_university_id" id="collaborator_university_id" placeholder="University id" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="collaborator_type">User type: </label>
            <input type="text" value="{{ profile.collaborator_type }}" class="form-control" name="collaborator_type" id="collaborator_type" placeholder="User type" required>
        </div>

        <div class="mb-3">
            <label class="form-label" for="collaborator_about">About: </label>
            <textarea class="form-control" name="collaborator_about" id="collaborator_about" placeholder="Collaborator about" rows="5" style="resize: vertical; overflow: hidden;" required>{{ profile.collaborator_about }}</textarea>
        </div>

        <script>
            const textarea = document.getElementById('collaborator_about');
            textarea.addEventListener('input', function() {
                this.style.height = 'auto';
                this.style.height = this.scrollHeight + 'px';
            });
            // Trigger on page load in case there's existing content
            textarea.style.height = 'auto';
            textarea.style.height = textarea.scrollHeight + 'px';
        </script>

        <button type="submit">Save Changes</button>
        <!--    login error message-->
        {% if messages %}

        {% for message in messages %}
        <br>
        <br>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}

        {% endif %}

    </form>

</div>

{% endblock %}

user/templates/user/user_profile.html
{% extends 'base.html' %}

{% block title %}
{% if user.is_authenticated %}
UniColabHub - {{user.username}}
{% else %}
Username
{% endif %}
{% endblock %}

{% block content %}
<div class="row py-5 px-4">
    <div class="col-md-7 mx-auto"> <!-- Profile widget -->
        <div class="bg-white shadow rounded overflow-hidden">
            <div class="px-4 pt-4 pb-4 cover">
                <div class="media align-items-end profile-head">
                    <div class="profile mr-3">
                        <div style="display:flex; align-items: start; column-gap: 20px;">

                            <div class="dropdown">
                              <button class="btn p-0 border-0" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    {% if profile.profile_pic %}
                                        <img src="{{ profile.profile_pic.url }}" alt="Profile Picture" class="rounded-circle" width="150" height="150" style="cursor: pointer; object-fit: cover;">
                                    {% else %}
                                        <img src="https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=Oliver" alt="No Profile Picture" class="rounded-circle" width="150" height="150" style="cursor: pointer; object-fit: cover;">
                                    {% endif %}
                              </button>
                              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" href="{% url 'user:update_profile_pic' %}">{% if profile.profile_pic.path != None %}Update{% else %}Add{% endif %}</a></li>
                                  {% if profile.profile_pic.path != None %}
                                    <li><a class="dropdown-item" href="{% url 'user:delete_profile_pic' %}">Delete</a></li>
                                  {% endif %}
                              </ul>
                            </div>


                            <div>

                                <p style="margin-bottom: 0;">@{{user.username}}</p>
                                <h4>
                                    {% if user.first_name or user.last_name %}
                                    {{user.first_name}} {{user.last_name}}
                                    {%else%}
                                    Update profile to show name
                                    {% endif %}
                                </h4>


                                <p>
                                    {% if profile.collaborator_university_id %}
                                    Reg: {{profile.collaborator_university_id}}
                                    {%else%}
                                    Update profile to show reg.
                                    {% endif %}
                                </p>
                                <a href="{% url 'user:update_profile'%}"
                                   class="btn btn-outline-dark btn-sm btn-block">Edit Profile</a>
                                <a href="{% url 'user:delete_user'%}"
                                   class="btn btn-outline-dark btn-sm btn-block">Delete Account</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="px-4 py-3">
                <h5 class="mb-0">About</h5>
                <div class="p-4 rounded shadow-sm bg-light">
                    <p class="font-italic mb-0">DOB: {{user.collabuser.collaborator_date_of_birth}}</p>
                    <p class="font-italic mb-0">About: {{user.collabuser.collaborator_about}}</p>
                </div>
            </div>
            <div class="px-4 py-3">
                <h5 class="mb-0">My Posts</h5>
                <div class="p-4 rounded shadow-sm bg-light">
                    <div class="container">
                        {% if user.is_authenticated %}

                        {% for item in feed_items %}
                          <div class="card mb-3 shadow-sm">
                              {% if item.cover_pic %}
                                <img src="{{ item.cover_pic.url }}" style="max-height: 25em; object-fit: cover;" class="card-img-top" alt="Cover image">
                              {% endif %}
                            <div class="card-body">

                                <h5 class="card-title">{{ item.title }}</h5>
                                <p class="text-muted"><i>By: {{ item.organizer.user.username }}</i></p>
                                <p class="text-black">Type: {{ item.content_type }} • Posted: {{ item.created_at|date:"M d, Y H:i" }}</p>
                                <p class="text-black">Description</p>
                                <p class="card-text">{{ item.description|truncatechars:150 }}</p>

                                <div class="d-flex">
                                    {% if item.content_type|lower == 'thesis' %}
                                        <div class="pe-3">
                                            <a href="{% url 'post:view_thesis' item.id %}" class="btn btn-primary mt-2">View {{ item.content_type }}</a>
                                        </div>

                                        {% if item.organizer.user == request.user %}
                                            <div class="pe-3">
                                                <a href="#" class="btn btn-primary mt-2">Edit {{ item.content_type }}</a>
                                            </div>

                                            <div class="pe-3">
                                                <a href="{% url 'post:delete_thesis' item.id %}" class="btn btn-primary mt-2">Delete {{ item.content_type }}</a>
                                            </div>

                                        {% endif %}
                                    {% elif item.content_type|lower == 'project' %}

                                        <div class="pe-3">
                                            <a href="{% url 'post:view_project' item.id %}" class="btn btn-primary mt-2">View {{ item.content_type }}</a>
                                        </div>
                                        {% if item.organizer.user == request.user %}

                                            <div class="pe-3">
                                                <a href="#" class="btn btn-primary mt-2">Edit {{ item.content_type }}</a>
                                            </div>

                                            <div class="pe-3">
                                                <a href="{% url 'post:delete_project' item.id %}" class="btn btn-primary mt-2">Delete {{ item.content_type }}</a>
                                            </div>
                                        {% endif %}
                                    {% elif item.content_type|lower == 'event' %}

                                        <div class="pe-3">
                                            <a href="{% url 'post:view_event' item.id %}" class="btn btn-primary mt-2">View {{ item.content_type }}</a>
                                        </div>
                                        {% if item.organizer.user == request.user %}

                                            <div class="pe-3">
                                                <a href="#" class="btn btn-primary mt-2">Edit {{ item.content_type }}</a>
                                            </div>

                                            <div class="pe-3">
                                                <a href="{% url 'post:delete_event' item.id %}" class="btn btn-primary mt-2">Delete {{ item.content_type }}</a>
                                            </div>
                                        {% endif %}
                                    {% endif %}
                                </div>

                            </div>
                          </div>
                        {% empty %}
                          <p>No posts yet.</p>
                        {% endfor %}

                        </div>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}