collaboration/urls.py
from django.urls import path
from . import views

app_name = 'collaboration'

urlpatterns = [
    path("add_resource/", views.add_resource, name="add_resource"),
    path('resource/<int:pk>/', views.view_resource, name='view_resource'),
    path('resource/<int:pk>/edit/', views.edit_resource, name='edit_resource'),
    path('resource/<int:pk>/delete_confirmation/', views.delete_resource, name='delete_resource'),
    path('resource/<int:pk>/delete/', views.confirm_delete, name='confirm_delete'),
    path('join_request/<int:pk>/', views.join_request, name='join_request'),
    path('review_request/<int:pk>/', views.review_request, name='review_request'),

]

post/urls.py
from django.urls import path
from .views import create_event, create_project,create_thesis, view_event, view_thesis, view_project, delete_event, delete_project, delete_thesis, edit_project, edit_event, edit_thesis

app_name = 'post'

urlpatterns = [
    path("create_event/", create_event, name="create_event"),
    path("create_project/", create_project, name="create_project"),
    path("create_thesis/", create_thesis, name="create_thesis"),
    path("view_event/<str:pk>", view_event, name="view_event"),
    path("view_project/<str:pk>", view_project, name="view_project"),
    path("view_thesis/<str:pk>", view_thesis, name="view_thesis"),
    path("delete_event/<str:pk>", delete_event, name="delete_event"),
    path("delete_project/<str:pk>", delete_project, name="delete_project"),
    path("delete_thesis/<str:pk>", delete_thesis, name="delete_thesis"),
    path("edit_event/<str:pk>", edit_event, name="edit_event"),
    path("edit_project/<str:pk>", edit_project, name="edit_project"),
    path("edit_thesis/<str:pk>", edit_thesis, name="edit_thesis"),
]

unicolabhub/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("home/", lambda request: redirect("home")),
    path('user/', include('user.urls')),
    path('post/', include('post.urls')),
    path('collaboration/', include('collaboration.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register_user, name='register_user'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('update_profile/', views.update_user, name='update_profile'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('update_profile_pic/', views.update_profile_pic, name='update_profile_pic'),
    path('delete_profile_pic/', views.delete_profile_pic, name='delete_profile_pic'),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <!--bootrstrap css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>

<!--global navbar-->
{% include 'navbar.html' %}

{% block content %}

{% endblock content %}


<!--bootstrap js-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}

    {% for item in feed_items %}
      <div class="card mb-3 shadow-sm">
          {% if item.cover_pic %}
            <img src="{{ item.cover_pic.url }}" style="max-height: 25em; object-fit: cover;" class="card-img-top" alt="Cover image">
          {% endif %}
        <div class="card-body">

            <h5 class="card-title">{{ item.title }}</h5>
            <p class="text-muted"><i>By: {{ item.organizer.user.username }}</i></p>
            <p class="text-black">Type: {{ item.content_type }} • Posted: {{ item.created_at|date:"M d, Y H:i" }}</p>
            <p class="text-black">Description</p>
            <p class="card-text">{{ item.description|truncatechars:150 }}</p>

            <div class="d-flex">
                {% if item.content_type|lower == 'thesis' %}
                    <div class="pe-3">
                        <a href="{% url 'post:view_thesis' item.id %}" class="btn btn-primary mt-2">View {{ item.content_type }}</a>
                    </div>

                    {% if item.organizer.user == request.user %}
                        <div class="pe-3">
                            <a href="{% url 'post:edit_thesis' item.id %}" class="btn btn-primary mt-2">Edit {{ item.content_type }}</a>
                        </div>

                        <div class="pe-3">
                            <a href="{% url 'post:delete_thesis' item.id %}" class="btn btn-primary mt-2">Delete {{ item.content_type }}</a>
                        </div>
                    {% endif %}
                {% elif item.content_type|lower == 'project' %}

                    <div class="pe-3">
                        <a href="{% url 'post:view_project' item.id %}" class="btn btn-primary mt-2">View {{ item.content_type }}</a>
                    </div>
                    {% if item.organizer.user == request.user %}

                        <div class="pe-3">
                            <a href="{% url 'post:edit_project' item.id %}" class="btn btn-primary mt-2">Edit {{ item.content_type }}</a>
                        </div>

                        <div class="pe-3">
                            <a href="{% url 'post:delete_project' item.id %}" class="btn btn-primary mt-2">Delete {{ item.content_type }}</a>
                        </div>
                    {% endif %}
                {% elif item.content_type|lower == 'event' %}

                    <div class="pe-3">
                        <a href="{% url 'post:view_event' item.id %}" class="btn btn-primary mt-2">View {{ item.content_type }}</a>
                    </div>
                    {% if item.organizer.user == request.user %}

                        <div class="pe-3">
                            <a href="{% url 'post:edit_event' item.id %}" class="btn btn-primary mt-2">Edit {{ item.content_type }}</a>
                        </div>

                        <div class="pe-3">
                            <a href="{% url 'post:delete_event' item.id %}" class="btn btn-primary mt-2">Delete {{ item.content_type }}</a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>

        </div>
      </div>
    {% empty %}
      <p>No posts yet.</p>
    {% endfor %}

    </div>
    {% endif %}

</div>
{% endblock%}

templates/login_form.html
<form method="POST" action="{% url 'home' %}">
    {% csrf_token %}
    <div class="mb-3">
        <input type="text" class="form-control" name="username" placeholder="Username" required>
    </div>
    <div class="mb-3">
        <input type="password" class="form-control" name="password" placeholder="Password" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>

    <!--    login error message-->
    {% if messages %}

    {% for message in messages %}
<br>
    <br>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
 {{message}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
    {% endfor %}

    {% endif %}


</form>

templates/navbar.html
<nav class="container navbar navbar-expand-lg bg-body-tertiary"
     style="box-shadow: rgba(0, 0, 0, 0.02) 0px 1px 3px 0px, rgba(27, 31, 35, 0.15) 0px 0px 0px 1px; border-radius: 5px;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">UniColabHub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'user:user_profile'%}">
                        {% if user.collabuser.profile_pic %}
                            <img src="{{ user.collabuser.profile_pic.url }}" alt="Profile Picture" class="rounded-circle" width="30" height="30" style="cursor: pointer; object-fit: cover;">
                        {% else %}
                            <img src="https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=Oliver" alt="No Profile Picture" class="rounded-circle" width="30" height="30" style="cursor: pointer; object-fit: cover;">
                        {% endif %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>

                {% endif%}
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item p-2">
                    <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Create
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'post:create_event' %}">Event</a></li>
                        <li><a class="dropdown-item" href="{% url 'post:create_project' %}">Project</a></li>
                        <li><a class="dropdown-item" href="{% url 'post:create_thesis' %}">Thesis</a></li>
                      </ul>
                    </div>
                </li>
                <li class="nav-item p-2">
                    <div class="dropdown">
                          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                            Notifications
                          </button>
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                              {% for notification in notifications %}
                            <li><a class="dropdown-item" href="{% url 'collaboration:review_request' notification.id %}">{{ notification.message }}</a></li>
                              {% endfor %}
                          </ul>
                    </div>
                </li>




                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout_user' %}">Logout</a>
                </li>
                {% endif%}

                {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>